- name: Configure webserver with nginx
  hosts: web-dev-001
  become: true
  tasks:
    - name: pull staff from git
      command: chdir=/root/labscicd git pull
    # Example checkout a github repo and use refspec to fetch all pull requests
    # - git:
    #     repo: https://github.com/saingsab/labscicd.git
    #     dest: /root/labscicd
    #     refspec: '+refs/pull/*:refs/heads/*'

    - name: Stop service nginx
      service: name=nginx state=stopped

    - name: Delete or backup current web
      command: rm -rf /var/www/html/

    - name: update web app dir
      command: cp -r /root/labscicd/webapp/ /var/www/html/

    - name: starting nginx
      service: name=nginx state=started