- name: Configure webserver with nginx
  hosts: web-dev-001
  become: true
  tasks:
    - name: Pull the latest codebase from GitHub
      ansible.builtin.git:
        repo: https://github.com/saingsab/labscicd.git
        dest: /root/labscicd
        version: dev

    - name: Stop service nginx
      service: name=nginx state=stopped

    - name: Delete or backup current web
      ansible.builtin.file:
        path: /var/www/html/*
        state: absent

    - name: Copy from latest codebase
      ansible.builtin.copy:
        src: /root/labscicd/webapp/
        dest: /var/www/html/
        owner: root
        group: root
        mode: '1777'

    - name: Start service nginx
      service: name=nginx state=started
