- name: Configure webserver with nginx
  hosts: web-dev-001
  become: True
  tasks:
    - name: pull staff from git
      command: chdir=/root/labscicd git pull

    - name: Stop service nginx
      service: name=nginx state=stopped 

    - name: update web app dir
      command: cp -r /root/labscicd/webapp/ /var/www/html/

    - name: starting nginx
      service: name=nginx state=started