name: Deploy Web

on:
  push:
    branches:
      - main
    # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-playbooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - shell: bash
        # run: |
        #   echo ${{ secrets.PRKEY }} > file.txt && cat file.txt
          run: |
            pwd && ls
