name: Deploy Web

on:
  push:
    branches:
      - main

jobs:
  echo-private-key-to-file:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo ${{ secrets.PRKEY }}
